export const LOG_MODULE_LABELS: Record<string, string> = {
  AUTH: '认证',
  USER: '用户',
  ROLE: '角色',
  MATERIAL: '物资',
  CATEGORY: '分类',
  SUPPLIER: '供应商',
  WAREHOUSE: '库区货位',
  INBOUND: '入库',
  OUTBOUND: '出库',
  OUTBOUND_PURPOSE: '出库用途',
  OUTBOUND_DESTINATION: '出库目的地',
  STOCK: '库存',
  ALERT: '预警',
}

export const LOG_ACTION_LABELS: Record<string, string> = {
  LOGIN: '登录',
  CREATE: '创建',
  UPDATE: '更新',
  DELETE: '删除',
  SUBMIT: '提交',
  APPROVE: '审核通过',
  REJECT: '驳回',
  RECEIVE: '收货',
  SHELVE: '上架',
  COMPLETE: '完成',
  PICK: '拣货',
  SHIP: '发运',
  SYNC: '同步',
  RESOLVE: '处理',
}

export const LOG_FIELD_LABELS: Record<string, string> = {
  username: '用户名',
  name: '姓名',
  phone: '电话',
  active: '状态',
  role: '角色',
  roleId: '角色',
  code: '编码',
  spec: '规格',
  model: '型号',
  unit: '单位',
  manufacturer: '生产厂家',
  categoryId: '分类',
  supplierId: '供应商',
  contact: '联系人',
  address: '地址',
  license: '资质',
  zone: '库区类型',
  area: '面积(㎡)',
  capacity: '容量',
  row: '排',
  level: '层',
  warehouseId: '所属库区',
  description: '说明',
  shelfLifeMonths: '保质期(月)',
  safetyStockMin: '安全库存下限',
  safetyStockMax: '安全库存上限',
  contractNo: '合同号',
  remark: '备注',
  purpose: '用途',
  destination: '目的地',
  city: '所属市',
  district: '所属区',
  recipient: '领用人',
  rejectReason: '驳回原因',
  status: '状态',
  type: '类型',
  lines: '明细',
  lineCount: '明细行数',
  permissions: '权限',
  password: '密码',
  sort: '排序',
  category: '分类',
  supplier: '供应商',
  images: '图片',
}

export const LOG_MODULES = Object.keys(LOG_MODULE_LABELS)
export const LOG_ACTIONS = Object.keys(LOG_ACTION_LABELS)
